import React, { useState, useEffect } from 'react';
import {
  Bell,
  ShieldAlert,
  Check,
  CheckCheck,
  Filter,
  Clock,
  Calendar,
  AlertTriangle,
  RotateCcw,
} from 'lucide-react';
import RiskBadge from '../components/RiskBadge';
import api from '../services/api';

export default function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [severityFilter, setSeverityFilter] = useState('ALL');
  const [loading, setLoading] = useState(true);

  const fetchAlerts = async (sev = severityFilter) => {
    try {
      const s = sev === 'ALL' ? null : sev;
      const data = await api.getAlerts(s, 100);
      setAlerts(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, []);

  const handleFilterChange = (sev) => {
    setSeverityFilter(sev);
    fetchAlerts(sev);
  };

  const handleAcknowledge = async (id, currentStatus) => {
    try {
      await api.acknowledgeAlert(id, !currentStatus);
      fetchAlerts(severityFilter);
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="panel p-5 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-mono uppercase tracking-widest text-rose-400 bg-rose-500/10 px-2 py-0.5 rounded">
              SPACE-WEATHER WARNING DISPATCH
            </span>
          </div>
          <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
            <Bell size={22} className="text-solar-400" />
            Solar Flare Alert Management & Audit Log
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Real-time critical, high, moderate, and watch notifications generated by inference models
          </p>
        </div>

        {/* Severity Filter Controls */}
        <div className="flex items-center gap-1.5 bg-space-950 p-1 rounded-lg border border-space-800 text-xs font-mono">
          {['ALL', 'CRITICAL', 'HIGH', 'MODERATE', 'WATCH', 'LOW'].map((s) => (
            <button
              key={s}
              onClick={() => handleFilterChange(s)}
              className={`px-2.5 py-1 rounded text-[11px] font-bold transition-all ${
                severityFilter === s
                  ? 'bg-solar-500 text-space-950 shadow-sm'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {s}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts Table */}
      <div className="panel p-5">
        <div className="flex items-center justify-between mb-4 border-b border-space-800 pb-3">
          <div className="flex items-center gap-2">
            <h3 className="text-sm font-bold text-white uppercase font-mono tracking-wider">
              Alert Notification History
            </h3>
            <span className="text-xs font-mono text-slate-500">
              ({alerts.length} records logged)
            </span>
          </div>

          <button
            onClick={() => fetchAlerts()}
            className="text-xs font-mono text-slate-400 hover:text-white flex items-center gap-1.5 transition-colors"
          >
            <RotateCcw size={12} />
            Refresh
          </button>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono border-collapse">
            <thead>
              <tr className="border-b border-space-800 text-slate-400 bg-space-950/70">
                <th className="p-3">Severity</th>
                <th className="p-3">Timestamp (UTC)</th>
                <th className="p-3">Horizon</th>
                <th className="p-3">Peak Prob</th>
                <th className="p-3">Nowcast State</th>
                <th className="p-3">Inference Engine</th>
                <th className="p-3">Message & Diagnostics</th>
                <th className="p-3 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-space-800/60">
              {alerts.length === 0 ? (
                <tr>
                  <td colSpan="8" className="p-6 text-center text-slate-500 font-mono">
                    No alert events found matching current filter.
                  </td>
                </tr>
              ) : (
                alerts.map((a) => {
                  const isCrit = a.severity === 'CRITICAL';
                  const isHigh = a.severity === 'HIGH';

                  return (
                    <tr
                      key={a.id}
                      className={`hover:bg-space-850/50 transition-colors ${
                        a.acknowledged ? 'opacity-60 bg-space-950/30' : isCrit ? 'bg-rose-950/15' : isHigh ? 'bg-orange-950/10' : ''
                      }`}
                    >
                      <td className="p-3">
                        <RiskBadge level={a.severity} size="sm" />
                      </td>
                      <td className="p-3 text-slate-300 whitespace-nowrap">
                        {new Date(a.timestamp).toLocaleString([], {
                          month: 'short',
                          day: '2-digit',
                          hour: '2-digit',
                          minute: '2-digit',
                          second: '2-digit',
                        })}
                      </td>
                      <td className="p-3 text-sky-400 font-bold whitespace-nowrap">
                        {a.forecast_horizon || '1h'}
                      </td>
                      <td className="p-3 font-bold text-solar-400">
                        {a.probability !== null && a.probability !== undefined
                          ? `${(a.probability * 100).toFixed(0)}%`
                          : '--'}
                      </td>
                      <td className="p-3 uppercase text-slate-300">
                        {a.nowcast_state || 'quiet'}
                      </td>
                      <td className="p-3 text-slate-400 text-[11px] truncate max-w-[120px]">
                        {a.model || 'cnn_lstm_fusion'}
                      </td>
                      <td className="p-3 text-slate-200 max-w-sm leading-relaxed">
                        {a.message}
                      </td>
                      <td className="p-3 text-right whitespace-nowrap">
                        <button
                          onClick={() => handleAcknowledge(a.id, a.acknowledged)}
                          className={`px-2.5 py-1 rounded text-[11px] font-mono border transition-all flex items-center gap-1 ml-auto ${
                            a.acknowledged
                              ? 'bg-space-950 text-slate-500 border-space-800 hover:text-slate-300'
                              : 'bg-space-800 hover:bg-space-700 text-slate-200 border-space-700 hover:border-solar-500'
                          }`}
                        >
                          {a.acknowledged ? (
                            <>
                              <CheckCheck size={12} className="text-emerald-400" />
                              Unack
                            </>
                          ) : (
                            <>
                              <Check size={12} className="text-solar-400" />
                              Acknowledge
                            </>
                          )}
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
